# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "create_font_annotations": "01_fontsampler.ipynb"}

modules = ["core.py",
           "fontsampler.py"]

doc_url = "https://kaljarv.github.io/aifont/"

git_url = "https://github.com/kaljarv/aifont/tree/master/"

def custom_doc_links(name): return None
